/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz1sistemasg2;

public class App {
    

    public static int calcularValorHora(String tipoVehiculo, int cantidadHoras){
        try {

            int valorHoras = 0;

                switch (tipoVehiculo){
                    case "C":
                        valorHoras = (int)(cantidadHoras * 5000);
                        break;
                    case "M":
                        valorHoras = (int)(cantidadHoras * 3000);
                        break;
                    case "B":
                        valorHoras = (int)(cantidadHoras * 1000);
                         break;
            }

            return (int)valorHoras; 

        } catch (Exception e) {

            return -1;
        }

    }

    public static double calcularDescuento(int valorTotalHoras, int estudiante, int cantidadHoras ){
        try {
            
            double valorDescuento = 0

            if(cantidadHoras > 4) {

                if(cantidadHoras == 5000) {
 
                    ValorDescuento = valorTotalHoras * 0.35;
 
                } else if(cantidadHoras == 3000) {
 
                    valorDescuento = valorTotalHoras * 0.35;
 
                } else if(cantidadHoras == 1000) {
 
                    ValorDescuento = valorTotalHoras * 0.35;
 
                }
 
            }
 
            return (int)valorDescuento;
 
        } catch(Exception e) {
 
            return -1;
 
        }
}
 
    public static double calcularIva(Double valorIva);{
        try{

            double valorIva = 0
        }






    }




    public static int calcularFactura(valorTotalHoras, valorDescuento){

        try {

            int valorFactura = valorHoras - ValorDescuento + valorIva;

            return (int)valorTotalFactura;

        } catch(Exception  e) {

            return -1;

        }
    }
    public static void main(String[] args) {
        try{
            Scanner sc = new Scanner(System.in);

            System.out.println
    
        
        
        }
    
        }
    }

    /*  Implemente una funcion llamada calcularValorHora que cumpla con las siguientes caracteristicas
        * Recibe: 
            - Una cadena de caracteres que representa el tipo de vehiculo (C, M o B)
            - Un entero que representa la cantidad de horas de permanencia
        * Retorna:
            - Un entero representando el valor total de las boletas
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------
    
    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularDescuento que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando la si es estudiante o no
            - Un entero represenatando la cantidad de horas
        * Retorna:
            - Un entero representando el valor del descuento
        * Controlar errores retornando -1
    */
    //------------------------------------------------------------------

    //------------------------------------------------------------------

    /*  Implemente una funcion llamada calcularFactura que cumpla con las siguientes caracteristicas
        * Recibe:
            - Un entero representando el valor total de las horas
            - Un entero representando el valor del descuento
        * Retorna:
            - Un entero representando el valor del total de la factura incluyendo el iva
    */
    //------------------------------------------------------------------
    


    //------------------------------------------------------------------

